// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OTE.Data.EFCore.Contexts;

#nullable disable

namespace Data.EFCore.Migrations
{
    [DbContext(typeof(OteContext))]
    [Migration("20260426223543_AllEntitiesAndDtos")]
    partial class AllEntitiesAndDtos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OTE.Data.EFCore.Entities.Argon2idPasswordEntity", b =>
                {
                    b.Property<int>("Argon2idPasswordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("argon2idPasswordId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Argon2idPasswordId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("createdAt");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasJsonPropertyName("hash");

                    b.Property<int>("Iterations")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("iterations");

                    b.Property<int>("MemoryCost")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("memoryCost");

                    b.Property<byte>("Parallelism")
                        .HasColumnType("smallint")
                        .HasJsonPropertyName("parallelism");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasJsonPropertyName("salt");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("userId");

                    b.Property<byte>("Version")
                        .HasColumnType("smallint")
                        .HasJsonPropertyName("version");

                    b.HasKey("Argon2idPasswordId");

                    b.HasIndex("UserId");

                    b.ToTable("Argon2idPasswords", "public");
                });

            modelBuilder.Entity("OTE.Data.EFCore.Entities.BookEntity", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("text")
                        .HasJsonPropertyName("isbn");

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasJsonPropertyName("authors");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deletedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasJsonPropertyName("description");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("publishDate");

                    b.Property<string>("Publishers")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasJsonPropertyName("publishers");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasJsonPropertyName("title");

                    b.HasKey("ISBN");

                    b.ToTable("Books", "public");
                });

            modelBuilder.Entity("OTE.Data.EFCore.Entities.BookListingEntity", b =>
                {
                    b.Property<int>("BookListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("bookListingId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookListingId"));

                    b.Property<string>("BookISBN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("isbn");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasJsonPropertyName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deletedAt");

                    b.Property<string>("Price")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasJsonPropertyName("price");

                    b.Property<string>("PurchaseType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasJsonPropertyName("purchaseType");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("userId");

                    b.HasKey("BookListingId");

                    b.HasIndex("BookISBN");

                    b.HasIndex("UserId");

                    b.ToTable("BookListings", "public");
                });

            modelBuilder.Entity("OTE.Data.EFCore.Entities.SchoolEntity", b =>
                {
                    b.Property<int>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("schoolId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SchoolId"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasJsonPropertyName("acronym");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasJsonPropertyName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deletedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasJsonPropertyName("name");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasJsonPropertyName("state");

                    b.HasKey("SchoolId");

                    b.ToTable("Schools", "public");
                });

            modelBuilder.Entity("OTE.Data.EFCore.Entities.SessionTokenCacheEntity", b =>
                {
                    b.Property<int>("SessionTokenCacheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SessionTokenCacheId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("createdAt");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("expiresAt");

                    b.Property<byte[]>("Token")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasJsonPropertyName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("userId");

                    b.HasKey("SessionTokenCacheId");

                    b.HasIndex("UserId");

                    b.ToTable("SessionTokens", "public");
                });

            modelBuilder.Entity("OTE.Data.EFCore.Entities.UserEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("userId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("deletedAt");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasJsonPropertyName("emailAddress");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasJsonPropertyName("firstName");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("isAdmin");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasJsonPropertyName("lastName");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasJsonPropertyName("middleName");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("schoolId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasJsonPropertyName("username");

                    b.HasKey("UserId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", "public");
                });

            modelBuilder.Entity("OTE.Data.EFCore.Entities.Argon2idPasswordEntity", b =>
                {
                    b.HasOne("OTE.Data.EFCore.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OTE.Data.EFCore.Entities.BookListingEntity", b =>
                {
                    b.HasOne("OTE.Data.EFCore.Entities.BookEntity", "Book")
                        .WithMany()
                        .HasForeignKey("BookISBN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OTE.Data.EFCore.Entities.UserEntity", "Seller")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("OTE.Data.EFCore.Entities.SessionTokenCacheEntity", b =>
                {
                    b.HasOne("OTE.Data.EFCore.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OTE.Data.EFCore.Entities.UserEntity", b =>
                {
                    b.HasOne("OTE.Data.EFCore.Entities.SchoolEntity", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });
#pragma warning restore 612, 618
        }
    }
}
