// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OTE.Data.EFCore.Contexts;

#nullable disable

namespace Data.EFCore.Migrations
{
    [DbContext(typeof(OteContext))]
    [Migration("20260117050706_ImprovedUsers")]
    partial class ImprovedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OTE.Data.EFCore.Entities.Argon2idPasswordEntity", b =>
                {
                    b.Property<int>("Argon2idPasswordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Argon2idPasswordId"));

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Iterations")
                        .HasColumnType("integer");

                    b.Property<int>("MemoryCost")
                        .HasColumnType("integer");

                    b.Property<byte>("Parallelism")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte>("Version")
                        .HasColumnType("smallint");

                    b.HasKey("Argon2idPasswordId");

                    b.ToTable("Argon2idPasswords", "public");
                });

            modelBuilder.Entity("OTE.Data.EFCore.Entities.SchoolEntity", b =>
                {
                    b.Property<int>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SchoolId"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("SchoolId");

                    b.ToTable("Schools", "public");
                });

            modelBuilder.Entity("OTE.Data.EFCore.Entities.UserEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<int>("Argon2idPasswordId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("UserId");

                    b.HasIndex("Argon2idPasswordId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("Username", "EmailAddress")
                        .IsUnique();

                    b.ToTable("Users", "public");
                });

            modelBuilder.Entity("OTE.Data.EFCore.Entities.UserEntity", b =>
                {
                    b.HasOne("OTE.Data.EFCore.Entities.Argon2idPasswordEntity", "Argon2idPassword")
                        .WithMany()
                        .HasForeignKey("Argon2idPasswordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OTE.Data.EFCore.Entities.SchoolEntity", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Argon2idPassword");

                    b.Navigation("School");
                });
#pragma warning restore 612, 618
        }
    }
}
